name: Deploy to VPS

on:
  push:
    branches: [main]  # Change to your branch if needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into AlmaLinux VPS and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script:
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/nordvolldev-to-github
          git pull origin main
          docker compose down
          docker compose build --no-cache
          docker compose up -d
